name: "Docker Build & Test"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build docker image
        run: docker build -t elcash-electrumx-ci .

      - name: pytest
        run: docker run --rm -w /source -e LOCAL_USER_ID=`id -u` -v "$(PWD):/source" elcash-electrumx-ci pytest --cov=electrumx

      - name: pycodestyle
        run: docker run --rm -w /source -e LOCAL_USER_ID=`id -u` -v "$(PWD):/source" elcash-electrumx-ci flake8 --exit-zero --max-line-length 100 --filename "./electrumx/**/*.py,./electrumx/*.py"
